---
- hosts: kubernetes-master-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Delete Role biniding RBAC
    shell: kubectl -n kube-system delete clusterrolebinding {{ service_account }}

  - name: Delete Service Account
    shell: kubectl -n kube-system delete sa {{ service_account }}

  - name: Reset Helm
    shell: helm reset --force --remove-helm-home
