---
- hosts: kubernetes-master-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Creating tiller Service Account
    shell: kubectl -n kube-system create serviceaccount {{ service_account }}

  - name: Creating Cluster Role Binding RBAC
    shell: kubectl create clusterrolebinding {{ service_account }} --clusterrole cluster-admin --serviceaccount=kube-system:{{ service_account }}
